### ISSUE TITLE
I love this game

### ISSUE THREAD

**Issue by guojing0** [anvoz/world-js#29]
I love this game, I think it is quite interesting and fun!

**Comment by anvoz** [comment]
Thank you so much. I wish I could have more time for this project. However, this is not a valid issue so I will close it soon. If you have any suggestion for this project, please send me an email or post it on Trello.

Email: anvo4888@gmail.com
Trello board: https://trello.com/b/cHyMmAaA/world-js

**Comment by guojing0** [comment]
Yeah, of course I will. I plan to learn js programming so I can contribute to this project. :)
